changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot[bot]
  categories:
    - title: "🚀 Features"
      labels:
        - enhancement
    - title: "🐛 Bug Fixes"
      labels:
        - bug
    - title: "🔒 Security Updates"
      labels:
        - security
    - title: "📦 Dependency Updates"
      labels:
        - dependencies
    - title: "📝 Documentation"
      labels:
        - documentation
    - title: "🔧 Tooling and CI"
      labels:
        - ci